name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: install_dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev

    - uses: actions/setup-go@v1
      with:
        go-version: '>=1.17.0'

    - name: Install Futhark
      run: |
          wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
          tar xf futhark-nightly-linux-x86_64.tar.xz
          (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
          echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Check versions
      run: |
        go version
        futhark --version

    - name: Build
      run: |
        make
