name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: install_dependencies
      run: |
        sudo apt-get install libsdl2-dev libsdl2-ttf-dev

    - uses: actions/setup-go@v1
      with:
        go-version: '>=1.17.0'

    - name: Install Futhark
      uses: diku-dk/install-futhark@v1.0.0

    - name: Check versions
      run: |
        go version
        futhark --version

    - name: Build
      run: |
        make
