name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v1

    - name: Install Futhark
      run: |
          wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
          tar xf futhark-nightly-linux-x86_64.tar.xz
          (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
          echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        make
